######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 27 12:03:05 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tetrismanager.h block.h mainwindow.h tetris.h
SOURCES += tetrismanager.cpp block.cpp main.cpp mainwindow.cpp tetris.cpp

QMAKE_CXXFLAGS += -std=c++11