######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 27 13:51:32 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += keypress.h
SOURCES += keypress.cpp main.cpp
