######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 15 15:20:33 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += brute.h fast.h mainwindow.h point.h
SOURCES += brute.cpp fast.cpp main.cpp mainwindow.cpp point.cpp
