######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 19 20:15:23 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
