######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 18 13:12:51 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . grid
INCLUDEPATH += . grid

# Input
HEADERS += grid/grid3d.h
SOURCES += grid/grid3d.cpp grid/main.cpp
