######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 20 14:03:41 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
