######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 19 20:22:43 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += notepad.h
SOURCES += main.cpp notepad.cpp
