######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 4 13:40:04 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += countdown.h
SOURCES += countdown.cpp main.cpp
