######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 26 16:41:35 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
